
import { Property, Lead, Client, Visit, DashboardStats, ChatMessage, LeadHistory, ClientStatus, SalesStage } from './types';

// --- DATA GENERATORS ---
const NAMES = ['Juan', 'Maria', 'Carlos', 'Ana', 'Luis', 'Sofia', 'Miguel', 'Lucia', 'Pedro', 'Elena'];
const SURNAMES = ['Garcia', 'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Perez', 'Sanchez'];

const CLIENT_STATUSES: ClientStatus[] = ['Frio', 'Tibio', 'Caliente', 'En seguimiento', 'Visita agendada', 'Cerrado', 'Perdido', 'Pausado', 'Derivado'];
const SALES_STAGES: SalesStage[] = ['Inicio', 'Indagación', 'Bajada producto', 'Seguimiento', 'Pre-cierre', 'Visita agendada', 'Visita realizada', 'Propuesta enviada', 'Negociación', 'Seña/Reserva', 'Cierre', 'Derivación humano', 'Perdido', 'Rechazado', 'Pausado'];

// PROPERTIES
export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    titulo: 'Moderna Casa en Nordelta',
    tipo: 'casa',
    tipo_operacion: 'venta',
    estado: 'publicada',
    fecha_alta_sistema: '2023-10-01',
    direccion_completa: 'Av. Del Golf 230, Nordelta, Tigre',
    calle: 'Av. Del Golf',
    altura: 230,
    barrio: 'Nordelta',
    zona: 'Norte',
    ciudad: 'Tigre',
    provincia: 'Buenos Aires',
    pais: 'Argentina',
    codigo_postal: '1670',
    ambientes: 6,
    dormitorios: 4,
    banos_completos: 5,
    toilettes: 2,
    cochera: true,
    cantidad_cocheras: 3,
    balcon: true,
    terraza: true,
    patio: true,
    jardin: true,
    quincho: true,
    parrilla: true,
    pileta: true,
    lavadero: true,
    baulera: true,
    sup_cubierta: 380,
    sup_total_lote: 450,
    ascensor: false,
    calefaccion: true,
    aire_acondicionado: true,
    seguridad: true,
    apto_profesional: false,
    acepta_mascotas: true,
    sum: true,
    gimnasio: true,
    pileta_comun: false,
    seguridad_24hs: true,
    agua: true,
    gas: true,
    cloacas: true,
    luz: true,
    internet: true,
    escritura: true,
    plano_aprobado: true,
    apto_credito: true,
    precio_venta: 850000,
    moneda: 'USD',
    acepta_permuta: true,
    publicada_mercadolibre: true,
    publicada_zonaprop: true,
    publicada_argenprop: true,
    publicada_web_america: true,
    fotos: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c'],
    foto_portada: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
    cantidad_consultas: 14,
    vistas_totales: 450,
    leads_generados: 12,
    created_at: '2023-10-01',
    updated_at: '2023-10-01',
  },
  {
    id: 'p2',
    titulo: 'Piso Exclusivo Recoleta',
    tipo: 'departamento',
    tipo_operacion: 'venta',
    estado: 'publicada',
    fecha_alta_sistema: '2023-10-02',
    direccion_completa: 'Av. Alvear 1800, Recoleta, CABA',
    calle: 'Av. Alvear',
    altura: 1800,
    barrio: 'Recoleta',
    zona: 'CABA',
    ciudad: 'CABA',
    provincia: 'Buenos Aires',
    pais: 'Argentina',
    codigo_postal: '1014',
    ambientes: 5,
    dormitorios: 3,
    banos_completos: 3,
    toilettes: 1,
    cochera: true,
    cantidad_cocheras: 2,
    balcon: true,
    terraza: false,
    patio: false,
    jardin: false,
    quincho: false,
    parrilla: false,
    pileta: false,
    lavadero: true,
    baulera: true,
    sup_cubierta: 260,
    sup_total_lote: 280,
    ascensor: true,
    calefaccion: true,
    aire_acondicionado: true,
    seguridad: true,
    apto_profesional: false,
    acepta_mascotas: true,
    sum: false,
    gimnasio: false,
    pileta_comun: false,
    seguridad_24hs: true,
    agua: true,
    gas: true,
    cloacas: true,
    luz: true,
    internet: true,
    escritura: true,
    plano_aprobado: true,
    apto_credito: true,
    precio_venta: 1200000,
    moneda: 'USD',
    acepta_permuta: false,
    publicada_mercadolibre: true,
    publicada_zonaprop: true,
    publicada_argenprop: true,
    publicada_web_america: true,
    fotos: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750'],
    foto_portada: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
    cantidad_consultas: 8,
    vistas_totales: 320,
    leads_generados: 5,
    created_at: '2023-10-02',
    updated_at: '2023-10-02',
  }
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    nombre: 'Juan Garcia',
    telefono: '+54 9 11 1234-5678',
    email: 'juan.garcia@email.com',
    fuente_consulta: 'Zonaprop',
    busca_venta: true,
    busca_alquiler: false,
    busca_inversion: false,
    busca_temporario: false,
    venta_tipo_propiedad: ['casa', 'duplex'],
    venta_zonas_interes: ['Nordelta', 'Santa Barbara'],
    venta_presupuesto_max: 500000,
    estado_temperatura: 'Caliente',
    etapa_proceso: 'Indagación',
    score: 85,
    probabilidad_cierre: 70,
    intenciones_detectadas: ['Mudanza rápida', 'Interés en Nordelta'],
    sentimiento_general: 'Positivo',
    nivel_engagement: 'Alto',
    recomendacion_ia: 'Enviar brochure de unidades similares en Nordelta.',
    cantidad_visitas_agendadas: 1,
    created_at: '2023-10-25T10:00:00Z',
    updated_at: '2023-10-25T10:00:00Z',
  }
];

export const MOCK_CLIENTS: any[] = MOCK_LEADS;

export const MOCK_STATS: DashboardStats = {
  totalLeads: 1245,
  qualifiedLeads: 350,
  visitsScheduled: 42,
  dealsClosed: 15,
  negotiationAmount: 8500000,
};

export const MOCK_VISITS: Visit[] = [
  {
    id: 'v1',
    lead_id: 'lead-1',
    lead_nombre: 'Juan Garcia',
    property_id: 'p1',
    property_titulo: 'Moderna Casa en Nordelta',
    vendedor_id: 'agent-1',
    fecha: '2023-11-05',
    hora: '10:00',
    estado: 'agendada',
    pipeline_stage: 'pendiente',
    created_at: '2023-10-25',
    updated_at: '2023-10-25'
  }
];